
module.exports = {
    articles: [
        {
            name: 'learn-react',
            title: 'The fatest way to learn react',
            content: ['Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?',
            ],
            votes: 0,
            comments: [],
            users: []
        },
        {
            name: 'best-react',
            title: 'Why is react the best framework?',
            content: ['Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?'
            ],
            votes: 0,
            comments: [],
            users: []
        },
        {
            name: 'top-react',
            title: 'Top 10 best react hooks',
            content: ['Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum molestiae repellat optio minima totam voluptatem fugit, vel necessitatibus dolor beatae doloribus, velit vero accusantium in? Necessitatibus vitae repellat officia magnam quae obcaecati nobis voluptates, voluptas itaque consectetur magni corporis quidem cupiditate optio ex modi facere iste rem explicabo soluta reprehenderit praesentium minus exercitationem ea. Aperiam error odit quod animi. Labore, harum facilis sit voluptate nam sunt quis tempore magni earum asperiores ratione amet, quisquam enim, tempora quam soluta maiores et officia. Quaerat dolor officiis assumenda quidem repellendus quae dolorem, est praesentium voluptate odio laboriosam repellat vero tempora, quo ab earum?'
            ],
            votes: 0,
            comments: [],
            users: []
        }
    ]
};
